config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :ingredients
  resources :restaurants do
    collection do
      get 'homepage'
      post 'homepage'
      get 'restaurant_info'
    end
  end
  resources :dishes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'restaurants#homepage'

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates_presence_of :description

  has_and_belongs_to_many :dishes
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:description)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% ingredient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="espacoLateral tamanhoForm">
    <div class="field form-group">
      <label>Description</label>
      <%= form.text_field :description,:class => "form-control"  %>
    </div>

    <div class="actions">
      <%= form.submit :class=>"btn btn-outline-success" %>
    </div>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<div class="espacoTopo espacoLateral">
  <%= link_to 'Show', @ingredient, class: "btn btn-outline-info" %>
  <%= link_to 'Back', ingredients_path, class: "btn btn-outline-dark" %>
</div>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<div class="espacoLateral">

  <h1>Ingredients</h1>

  <table class="table table-hover">
    <thead>
    <tr>
      <th scope="col">Description</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td scope="row" ><%= ingredient.description %></td>
        <td>
          <div class="button-group">
            <%= link_to 'Show', ingredient, :class => "btn btn-outline-info"  %>
            <%= link_to 'Edit', edit_ingredient_path(ingredient), class: "btn btn-outline-secondary" %>
            <%= link_to 'Destroy', ingredient, :class => "btn btn-outline-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= link_to 'New Ingredient', new_ingredient_path, :class => "btn btn-outline-success " %>
</div>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<div class="espacoLateral espacoTopo">
  <%= link_to 'Back', ingredients_path, class: "btn btn-outline-secondary" %>
</div>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>


<div class="espacoLateral espacoTopo">
  <div class="card border-dark mb-3" style="max-width: 18rem;">
    <div class="card-header bg-transparent border-dark"><h2>Ingredient</h2></div>
    <div class="card-body text-dark">
      <p class="card-text justify-content-center">
        <%= @ingredient.description %>
      </p>
    </div>
    <div class="card-footer bg-transparent border-dark align-self-center">
      <%= link_to 'Edit', edit_ingredient_path(@ingredient), class: "btn btn-outline-success" %>
      <%= link_to 'Back', ingredients_path, class: "btn btn-outline-secondary" %>
    </div>
  </div>
</div>