config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :ingredients
  resources :restaurants do
    collection do
      get 'homepage'
      post 'homepage'
      get 'restaurant_info'
    end
  end
  resources :dishes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'restaurants#homepage'

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name, :address, :phone

  has_many :dishes
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  def search_dish(term)
    $dish = term
  end

  def homepage
    @restaurant = Restaurant.all.order("name")

    @restaurant = @restaurant.joins("INNER JOIN dishes ON dishes.restaurant_id = restaurants.id INNER JOIN categories ON categories.id = dishes.category_id  and UPPER(categories.description) like", "'%#{params[:search_term1].to_s.upcase}%'") unless params[:search_term1].blank?

    @restaurant = @restaurant.joins("INNER JOIN dishes ON dishes.restaurant_id = restaurants.id AND UPPER(dishes.description) like ", "'%#{params[:search_term2].to_s.upcase}%'") unless params[:search_term2].blank?

    @restaurant = @restaurant.joins("INNER JOIN dishes ON dishes.restaurant_id = restaurants.id AND dishes.category_id = ", params[:category_id]).distinct unless params[:category_id].blank?

    search_dish(params[:search_term2].to_s)
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def restaurant_info
    @restaurant = Restaurant.find(params[:restaurant_id])

    @dishes = Dish.where("restaurant_id = ?", params[:restaurant_id])
    @search = $dish
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper

end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="espacoLateral tamanhoForm">
    <div class="field form-group">
      <label>Name</label>
      <%= form.text_field :name,:class => "form-control"  %>
    </div>

    <div class="field form-group">
      <label>Address</label>
      <%= form.text_field :address,:class => "form-control"  %>
    </div>

    <div class="field form-group">
      <label>Phone</label>
      <%= form.text_field :phone,:class => "form-control"  %>
    </div>

    <div class="actions">
      <%= form.submit :class=>"btn btn-outline-success" %>
    </div>
  </div>

<% end %>

app/views/restaurants/edit.html.erb
<h1 class="espacoLateral float_center">Edit Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<div class="espacoTopo espacoLateral">
  <%= link_to 'Show', @restaurant, class: "btn btn-outline-info" %>
  <%= link_to 'Back', restaurants_path, class: "btn btn-outline-dark" %>
</div>

app/views/restaurants/homepage.html.erb
<div class="pgMain">
  <div class="categories">
    <div class="header">
      <h2><%=link_to 'Categories', root_path, class: "link-titulo", :class => "link-header"  %></h2>
    </div>
    <div class="list">
      <ul>
        <% Category.all.order("description").each do |category| %>
          <li>
            <%= link_to category.description, homepage_restaurants_path(category_id: category.id), :class =>  "link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="search">
    <div class="content">
      <%= form_tag homepage_restaurants_path, :placeholder =>"Category", :method => 'post', :class => "nav-item align-middle" do %>
        <p>
          <label>Search Categories</label><br>
          <%= text_field_tag( :search_term1) %>
          <%= submit_tag "Seach", :class => "btn btn-outline-primary align-middle"%>
        </p>
      <% end %>

      <%= form_tag homepage_restaurants_path, :method => 'post', :class => "nav-item align-middle" do %>
        <p>
          <label>Search Dishes</label><br>
          <%= text_field_tag( :search_term2)%>
          <%= submit_tag "Seach", :class => "btn btn-outline-primary align-middle"%>
        </p>
      <% end %>
    </div>
  </div>

  <div class="restaurants" >

    <h2><%=link_to 'Restaurants', root_path, :class => "link-header"  %></h2>

    <div class="list" >
        <ul>
          <% @restaurant.order("name").each do |restaurant| %>
            <li><%= link_to restaurant.name, restaurant_info_restaurants_path(restaurant_id: restaurant.id), :class =>  "link" %></li>
          <% end %>
        </ul>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<div class="espacoLateral">

  <h1>Restaurants</h1>

  <table class="table table-hover">
    <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Address</th>
      <th scope="col">Phone</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td scope="row" ><%= restaurant.name %></td>
        <td scope="row" ><%= restaurant.address %></td>
        <td scope="row" ><%= restaurant.phone %></td>
        <td scope="row">
          <div class="button-group">
            <%= link_to 'Show', restaurant, :class => "btn btn-outline-info" %>
            <%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn btn-outline-secondary" %>
            <%= link_to 'Destroy', restaurant, :class => "btn btn-outline-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Restaurant', new_restaurant_path, :class => "btn btn-outline-success "  %>
</div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<div class="espacoLateral espacoTopo">
  <%= link_to 'Back', restaurants_path, class: "btn btn-outline-secondary" %>
</div>

app/views/restaurants/restaurant_info.html.erb
<h2 class="text-center"><%= @restaurant.name %></h2>
<h6 class="text-center"><%= @restaurant.address %></h6>
<h6 class="text-center"><%= @restaurant.phone %></h6>

                      <hr>

<div class="box-content">
<% @dishes.all.each do |dishes| %>
    <div class="box">
      <div class="espacoLateral espacoTopo">
        <div class="card border-dark mb-3" style="max-width: 18rem;">
          <div class="card-header bg-transparent border-dark text-center">
            <h2><%=  highlight(dishes.description,@search) %></h2>
          </div>

          <div class="card-body text-dark">
            <p class="card-text">
            <small><b>Tempo de Produção:</b> <%= dishes.time %></small>
            <br>
            <small><b>Ingredientes:</b> <%= dishes.ingredients.map(&:description).join(', ') %></small>
            </p>
          </div>
          <div class="card-footer text-center">
            <h6>R$ <%= dishes.price %></h6>
          </div>
        </div>
      </div>
    </div>
<% end %>

</div>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<div class="espacoLateral espacoTopo">
  <div class="card border-dark mb-3" style="max-width: 18rem;">
    <div class="card-header bg-transparent border-dark"><h2><%= @restaurant.name %></h2></div>
    <div class="card-body text-dark">
      <p class="card-text">
      <h6>Address: <%= @restaurant.address %></h6>
      <h6>Address: <%= @restaurant.phone %></h6>
      </p>
    </div>
    <div class="card-footer bg-transparent border-dark align-self-center">
      <%= link_to 'Edit', edit_restaurant_path(@restaurant), class: "btn btn-outline-success" %>
      <%= link_to 'Back', restaurants_path, class: "btn btn-outline-secondary" %>
    </div>
  </div>
</div>