config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :ingredients
  resources :restaurants do
    collection do
      get 'homepage'
      post 'homepage'
      get 'restaurant_info'
    end
  end
  resources :dishes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'restaurants#homepage'

end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light" >
  <div class="collapse navbar-collapse " id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Homepage', root_path, class: "navbar-brand nav-link" %><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <%= link_to('Restaurant', restaurants_path, class: " nav-link navbar-brand")%>
      </li>
      <li class="nav-item active">
        <%= link_to('Dishes', dishes_path, class: "navbar-brand nav-link")  %>
      </li>
      <li class="nav-item active">
        <%= link_to('Ingredients', ingredients_path, class: "navbar-brand nav-link") %>
      </li>
      <li class="nav-item active">
        <%= link_to('Categories', categories_path, class: "navbar-brand nav-link") %>
      </li>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindFood</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render '/layouts/navigation' %>
    </header>
      <%= yield %>
  </body>
</html>